### PR TITLE
Modified Task 3 - Performing Sentiment Analysis to modify Sentiment API URL

### PR DESCRIPTION
**Pull request by amalgireesh**
changed the sentiment API URL to use URL +/text/analytics/v2.1/sentiment

### CODE REVIEW

**Comment by amalgireesh** [comment]
@DawnmarieDesJardins Hi, Dawnmarie 
There are workshops coming up,Can you please look into this ASAP.

**Comment by DawnmarieDesJardins** [comment]
@amalgireesh 
Thanks Amal,  I've asked one of our authors to review.  Please note that our SLA is 5 - 10 business days for review and resolution of issues and we ask only our content authors create pull requests.  Please provide the date of your workshop and we will do our best to close this by then.

**Comment by amalgireesh** [comment]
@DawnmarieDesJardins 
Hi Marie, We have lab scheduled on 12/09/2019 with 100+ attendees,can you please check/fix this ASAP.

**Comment by timahenning** [comment]
We believe the URL update is correct.  Please merge.

Tim

**Pull request merged**
